/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of IRC.xs. Do not edit this file, edit IRC.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "IRC.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <irc.h> /* irc.* interface */

typedef struct irc * IRC;

#include "const-c.inc"

#line 23 "IRC.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 75 "IRC.c"

/* INCLUDE:  Including 'const-xs.inc' from 'IRC.xs' */


XS(XS_IRC_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 104 "IRC.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid IRC macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined IRC macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing IRC macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 180 "IRC.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'IRC.xs' from 'const-xs.inc' */


XS(XS_IRC_target); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_target)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::target",
			"event", "IRC");
#line 21 "IRC.xs"
        RETVAL = irc.target(event);
#line 215 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_text); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_text)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::text",
			"event", "IRC");
#line 29 "IRC.xs"
        RETVAL = irc.text(event);
#line 247 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_nick); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_nick)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::nick",
			"event", "IRC");
#line 37 "IRC.xs"
        RETVAL = irc.nick(event);
#line 279 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_real); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_real)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::real",
			"event", "IRC");
#line 45 "IRC.xs"
        RETVAL = irc.real(event);
#line 311 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_host); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_host)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::host",
			"event", "IRC");
#line 53 "IRC.xs"
        RETVAL = irc.host(event);
#line 343 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_servername); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_servername)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::servername",
			"event", "IRC");
#line 61 "IRC.xs"
        RETVAL = irc.server(event);
#line 375 "IRC.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_IRC_raw); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_raw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "event, text");
    {
	IRC	event;
	const char *	text = (const char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::raw",
			"event", "IRC");
#line 71 "IRC.xs"
        RETVAL = irc.raw(event, text);
#line 408 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_IRC_say); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_say)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "event, text");
    {
	IRC	event;
	const char *	text = (const char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::say",
			"event", "IRC");
#line 80 "IRC.xs"
        RETVAL = irc.say(event, text);
#line 441 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_IRC_privmsg); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_privmsg)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "event, target, text");
    {
	IRC	event;
	const char *	target = (const char *)SvPV_nolen(ST(1));
	const char *	text = (const char *)SvPV_nolen(ST(2));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::privmsg",
			"event", "IRC");
#line 90 "IRC.xs"
        RETVAL = irc.privmsg(event, target, text);
#line 475 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_IRC_privmsg_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_privmsg_server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "event, server, target, text");
    {
	IRC	event;
	const char *	server = (const char *)SvPV_nolen(ST(1));
	const char *	target = (const char *)SvPV_nolen(ST(2));
	const char *	text = (const char *)SvPV_nolen(ST(3));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::privmsg_server",
			"event", "IRC");
#line 101 "IRC.xs"
        RETVAL = irc.privmsg_server(event, server, target, text);
#line 510 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_IRC_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_connect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "event, nick, user, host, port, ssl");
    {
	IRC	event;
	const char *	nick = (const char *)SvPV_nolen(ST(1));
	const char *	user = (const char *)SvPV_nolen(ST(2));
	const char *	host = (const char *)SvPV_nolen(ST(3));
	unsigned int	port = (unsigned int)SvUV(ST(4));
	int	ssl = (int)SvIV(ST(5));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::connect",
			"event", "IRC");
#line 114 "IRC.xs"
        RETVAL = irc.connect(event, nick, user, host, port, ssl);
#line 547 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_IRC_reload); /* prototype to pass -Wmissing-prototypes */
XS(XS_IRC_reload)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "event");
    {
	IRC	event;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "IRC")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    event = INT2PTR(IRC,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"IRC::reload",
			"event", "IRC");
#line 122 "IRC.xs"
        RETVAL = irc.reload(event);
#line 579 "IRC.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_IRC); /* prototype to pass -Wmissing-prototypes */
XS(boot_IRC)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("IRC::constant", XS_IRC_constant, file);
        newXS("IRC::target", XS_IRC_target, file);
        newXS("IRC::text", XS_IRC_text, file);
        newXS("IRC::nick", XS_IRC_nick, file);
        newXS("IRC::real", XS_IRC_real, file);
        newXS("IRC::host", XS_IRC_host, file);
        newXS("IRC::servername", XS_IRC_servername, file);
        newXS("IRC::raw", XS_IRC_raw, file);
        newXS("IRC::say", XS_IRC_say, file);
        newXS("IRC::privmsg", XS_IRC_privmsg, file);
        newXS("IRC::privmsg_server", XS_IRC_privmsg_server, file);
        newXS("IRC::connect", XS_IRC_connect, file);
        newXS("IRC::reload", XS_IRC_reload, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

